# Generated by Django 4.0.5 on 2022-06-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='shop.characteristictype'),
        ),
    ]
